### ISSUE TITLE
timezone import issue

### ISSUE THREAD

**Issue by tielur** [foobuzz/todo#1]
I'm getting the current error when trying to use the `todo` cli:

Python 2.7.11

```
Traceback (most recent call last):
  File "/usr/local/bin/todo", line 7, in <module>
    from todo import main
  File "/usr/local/lib/python2.7/site-packages/todo.py", line 5, in <module>
    from datetime import datetime, timezone, timedelta
ImportError: cannot import name timezone
```

**Comment by brandonb927** [comment]
It looks like maybe only Python3 is supported? This is in the `README`:
```
Install the todocli package for Python 3 via pip.
```

**Comment by tielur** [comment]
Makes sense...

I didn't realize that python 3+ was a separate package in `brew` on OSX. I've installed Python 3.5.1 via `brew install python3` and then installed todocli via `pip3 install todocli` and everything is working now!
