### ISSUE TITLE
Consider add new todo title without quotation marks

### ISSUE THREAD

**Issue by dramon** [foobuzz/todo#11]
It would be nice if something like this works:
```
$ todo add Install Squid
$ todo add Install Nginx' -c django
```

**Comment by foobuzz** [comment]
Hello,

For the sake of simplicity, and to stay standard with how arguments are understood by the command-line, I decided that I won't implement this change. It adds quite a deal of complexity on the command parsing part, for little benefit in my opinion. Thank you for the suggestion though.

**Comment by dramon** [comment]
OK. Thanks for your time.
