### ISSUE TITLE
No way to unmark task as done

### ISSUE THREAD

**Issue by jilleJr** [foobuzz/todo#17]
Small note from when I tried using this: There doesn't seem to be a way to unmark a task as done.

I did a typo and marked the wrong task as done. Would be nice if `todo done` toggled the status of the task, or if there was a command such as `todo undone`

**Comment by ShadiestGoat** [comment]
Perhaps it would be best to have a `todo undo`? That way, you store a minimum amount of things?

**Comment by foobuzz** [comment]
Hello!

I just release version 4.0.0 with the `undone` command :)

**Comment by jilleJr** [comment]
@foobuzz oh hey that's awesome!
