### ISSUE TITLE
Multiple machines

### ISSUE THREAD

**Issue by rmchale** [foobuzz/todo#2]
Does todo work on multiple machines? Can the database be shared in Dropbox?

**Comment by foobuzz** [comment]
Sorry, it doesn't work with multiple machines. You can migrate the todolist to another installation though. The database is stored in `~/.toduh/data.json`, which you can copy in the same directory in another user account.

**Comment by benswinburne** [comment]
You can put the database into dropbox and symlink it's normal location to your shared copy. You obviously might get problems when syncing etc as it's not designed to be used concurrently by multiple machines/users but at the very least it's backed up.

    mkdir -p ~/Dropbox/.toduh/
    mv ~/.toduh/data.json ~/Dropbox/.toduh/data.json
    ln -s ~/Dropbox/.toduh/data.json ~/.toduh/data.json

**Comment by rmchale** [comment]
Thanks, I was thinking about the symlink approach.  I'll give that a try.
