### ISSUE TITLE
Error After Install

### ISSUE THREAD

**Issue by jwood803** [foobuzz/todo#3]
Installed via `pip` and when typing in `todo` I get the below error.

```
Traceback (most recent call last):
  File "/usr/local/bin/todo", line 7, in <module>
    from todo import main
  File "/Library/Python/2.7/site-packages/todo.py", line 5, in <module>
    from datetime import datetime, timezone, timedelta
ImportError: cannot import name timezone
```

**Comment by baybatu** [comment]
https://github.com/foobuzz/todo/issues/1

**Comment by jwood803** [comment]
Whoops! Not sure how I missed that one. Got it working after going through @tielur's comments. If it's cool, I may update the readme to make it a bit clearer to folks who aren't familiar with `pip`, like myself.
