### ISSUE TITLE
Consider adding/changing task addition and deletion cli syntax

### ISSUE THREAD

**Issue by Grokzen** [foobuzz/todo#5]
Hi, great app.

Would you coonsider to add or change the existing way to add and delete tasks from the current one `todo -a foobar` to something that feels more natural `todo add foobar`? Possibly, both formats can be supported out of the box.

**Comment by foobuzz** [comment]
Hi, thanks!

This is a nice idea which I plan to roll out in version 2 (I'm going to update the Roadmap to reflect this decision). For the sake of consistency, I'll remove the -a option and use the following template for all commands:

`todo <command> <value> [<options>]`

For example we'll have `todo add ...` for adding a task, `todo done ...` for marking a task as done, etc.
