### ISSUE TITLE
Edited todo item is not saved

### ISSUE THREAD

**Issue by JadenGeller** [foobuzz/todo#7]
I use :x to exit vim, but the modified todo item is not reflected in the list.

**Comment by foobuzz** [comment]
I cannot reproduce. Any specific steps or content to put in the editor?

**Comment by foobuzz** [comment]
While I can't reproduce the bug on my environment, I've noticed this bit in the NamedTemporaryFile documentation (which I use to generate the file that vim will edit) : "Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms". I've replaced it with a custom and simple temporary file function that creates a temporary file in the todo directory. This should work now.
